# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x15\n\x08SumReply\x12\t\n\x01s\x18\x01 \x01(\x01\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\" \n\rMultiplyReply\x12\x0f\n\x07product\x18\x01 \x01(\x01\"1\n\x0eMaximumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"\x1f\n\x0cMaximumReply\x12\x0f\n\x07maximum\x18\x01 \x01(\x01\"2\n\rDivideRequest\x12\x10\n\x08\x64ividend\x18\x01 \x01(\x01\x12\x0f\n\x07\x64ivisor\x18\x02 \x01(\x01\"2\n\x0b\x44ivideReply\x12\x10\n\x08quotient\x18\x01 \x01(\x03\x12\x11\n\tremainder\x18\x02 \x01(\x01\x32\xac\x01\n\nCalculator\x12\x1d\n\x03Sum\x12\x0b.SumRequest\x1a\t.SumReply\x12,\n\x08Multiply\x12\x10.MultiplyRequest\x1a\x0e.MultiplyReply\x12)\n\x07Maximum\x12\x0f.MaximumRequest\x1a\r.MaximumReply\x12&\n\x06\x44ivide\x12\x0e.DivideRequest\x1a\x0c.DivideReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMREQUEST']._serialized_start=20
  _globals['_SUMREQUEST']._serialized_end=54
  _globals['_SUMREPLY']._serialized_start=56
  _globals['_SUMREPLY']._serialized_end=77
  _globals['_MULTIPLYREQUEST']._serialized_start=79
  _globals['_MULTIPLYREQUEST']._serialized_end=118
  _globals['_MULTIPLYREPLY']._serialized_start=120
  _globals['_MULTIPLYREPLY']._serialized_end=152
  _globals['_MAXIMUMREQUEST']._serialized_start=154
  _globals['_MAXIMUMREQUEST']._serialized_end=203
  _globals['_MAXIMUMREPLY']._serialized_start=205
  _globals['_MAXIMUMREPLY']._serialized_end=236
  _globals['_DIVIDEREQUEST']._serialized_start=238
  _globals['_DIVIDEREQUEST']._serialized_end=288
  _globals['_DIVIDEREPLY']._serialized_start=290
  _globals['_DIVIDEREPLY']._serialized_end=340
  _globals['_CALCULATOR']._serialized_start=343
  _globals['_CALCULATOR']._serialized_end=515
# @@protoc_insertion_point(module_scope)
